---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ikanhia1/public_html/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R cart $DEPLOYPATH
    - /bin/cp -R Midtrans $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp detail.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
    - /bin/cp logout.php $DEPLOYPATH
    - /bin/cp midtrans_init.php $DEPLOYPATH
    - /bin/cp midtrans-notification-handler.php $DEPLOYPATH
    - /bin/cp Midtrans.php $DEPLOYPATH
    - /bin/cp proyekpw_lib.php $DEPLOYPATH
    - /bin/cp register.php $DEPLOYPATH
    - /bin/cp user_history.php $DEPLOYPATH